### ISSUE TITLE
Margin with mobile

### ISSUE THREAD

**Issue by aysedemirel** [aysedemirel/AtaturkTributePage#1]
Left  and right margins are too large and the content is not centered in mobile device

**Comment by aditya28sarin** [comment]
Can you assign this issue to me?

**Comment by aysedemirel** [comment]
Okay, thank you

**Comment by aditya28sarin** [comment]
I have centered the text and also reduced the margin in mobile version, can you merge the PR?

**Comment by aysedemirel** [comment]
Thank you
